PIN_PWM_LED = 18
PIN_BUTTON = 27
PIN_LIGHTSENSOR = 4
PIN_MOTIONSENSOR = 0

[screensaver]
DISPLAY = ':0.0'

[button]
MIN_HOLD_TIME_SECONDS = 0.5
MAX_HOLD_TIME_SECONDS = 5.0

[led]
LED_MAX = 1.0
LED_MIN = 0.1
FPS = 25

[brightness]
POLL_TIME_SECONDS = 5.0
SMOOTH = true
SMOOTH_DURATION_SECONDS = 1.0
SMOOTH_FPS = 25
AUTO_ENABLED = false
AUTO_MINIMUM = 50
AUTO_MAXIMUM = 255
AUTO_STEP_COUNT = 15
MANUAL_STEPS = [ 50, 100, 150, 200, 250 ]

[shutdown]
SCRIPT_CMD = 'python ./shutdown_menu.py'
TIMEOUT = 5.0
